### PR TITLE
Merging of Desy P11 Config

### PR DESCRIPTION
**Pull request by jurbschat**
Merging of Desy P11 Config

### CODE REVIEW

**Review by IvarsKarpics — CHANGES_REQUESTED** [review]
Could you please make a separate PR for changing the BlissFramework/Bricks/Qt4_MotorSpinBoxBrick.py  ? Otherwise I am fine to merge the configuration.

**Comment by jurbschat** [comment]
should i make two new pull requests (one for the config one for the brick) or can you ignore that one file and pull in the rest?

**Comment by IvarsKarpics** [comment]
Yes, please create two new pull requests. For the config PR please do not modify the session.xml in the ExampleFiles/HardwareObjects.xml, You are free to create your own config in the site specific directory.

**Comment by marcus-oscarsson** [comment]
The easiest way would probably just be to create a new branch from your current master and remove the commits you don't want. for instance with:

    git rebase -i origin/master

Since you are new to the project and we have a bunch of other PRs to look at, I would be fine with letting this go and merge as long as there are no issues with the PR. @IvarsKarpics is there anything with the Qt4_MotorSpinBoxBrick that you would like to change ?

**Comment by jurbschat** [comment]
i just created the new pull requests #274 and #275, i hope this works?

**Comment by IvarsKarpics** [comment]
You are right @marcus-oscarsson . I should not have been so harsh... Thanks for extra work. I will check the separate PRs.

**Pull request closed without merging**
