### PR TITLE
snake_case, some fixes, some mockup refactoring. Program now opens.

### PR DESCRIPTION
**Pull request by rhfogh**
Sister PR to HardwareRepository PR #494

See #494 for description

### CODE REVIEW

**Review by IvarsKarpics — APPROVED** [review]

**Comment by IvarsKarpics** [comment]
I am fine with PR. Maybe @natxo14  could have a look.

**Comment by natxo14** [comment]
Fine also for me, good to go!

ps: just a question, only curious about it. 
Changes from:
        `super().__init__(*args)`
to : 
        `super(TurretBrick, self).__init__(*args)`

are just a matter of style (more meaningful) or trying to make it python2 compatible or as no multiple inheritance is demanded or ...??

**Comment by rhfogh** [comment]
@natxo14 
super().\_\_init\_\_() is a much better style IMHO, but unfortunately Python 2 does not support it. Once we are fully into Python 3 we can do it the nice way.

**Comment by beteva** [comment]
> Fine also for me, good to go!
> 
> ps: just a question, only curious about it.
> Changes from:
> `super().__init__(*args)`
> to :
> `super(TurretBrick, self).__init__(*args)`
> 
> are just a matter of style (more meaningful) or trying to make it python2 compatible or as no multiple inheritance is demanded or ...??

Python 2.7 compatible

**Comment by marcus-oscarsson** [comment]
@natxo14, yes super().__init__() is in my opinion also nicer, but we have to live with the other alternative for a little longer :)

**Comment by jordiandreu** [comment]
I have tested this PR with its  sister PR and looks also fine to me.

**Comment by jordiandreu** [comment]
@rhfogh Thanks for this work!

**Comment by rhfogh** [comment]
Thanks again!

**Pull request merged**
