### PR TITLE
Submodule update

### PR DESCRIPTION
**Pull request by IvarsKarpics**

### CODE REVIEW

**Comment by IvarsKarpics** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity decreasing per file
==============================
+ gui/GUISupervisor.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/mxcube/mxcube/pullRequest?prid=4541283&bid=15284487)

**Comment by IvarsKarpics** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ gui/GUISupervisor.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/mxcube/mxcube/pullRequest?prid=4541283&bid=15284487)

**Review by rhfogh — APPROVED** [review]
Not tested, but looks correect.
Thanks.

**Comment by IvarsKarpics** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ gui/GUISupervisor.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/mxcube/mxcube/pullRequest?prid=4541283&bid=15284487)

**Comment by IvarsKarpics** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ gui/GUISupervisor.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/mxcube/mxcube/pullRequest?prid=4541283&bid=15284487)

**Comment by IvarsKarpics** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ gui/GUISupervisor.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/mxcube/mxcube/pullRequest?prid=4541283&bid=15284487)

**Comment by IvarsKarpics** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ gui/GUISupervisor.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/mxcube/mxcube/pullRequest?prid=4541283&bid=15284487)

**Comment by IvarsKarpics** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ gui/GUISupervisor.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/mxcube/mxcube/pullRequest?prid=4541283&bid=15284487)

**Comment by IvarsKarpics** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ gui/GUISupervisor.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/mxcube/mxcube/pullRequest?prid=4541283&bid=15284487)

**Comment by IvarsKarpics** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ gui/GUISupervisor.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/mxcube/mxcube/pullRequest?prid=4541283&bid=15284487)

**Comment by IvarsKarpics** [comment]
Thanks @rhfogh . I have some problems with pylint (it gets stucked when checking the bricks). When I resolve the issue I will merge the PR.

**Comment by IvarsKarpics** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ gui/GUISupervisor.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/mxcube/mxcube/pullRequest?prid=4541283&bid=15284487)

**Comment by IvarsKarpics** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ gui/GUISupervisor.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/mxcube/mxcube/pullRequest?prid=4541283&bid=15284487)

**Pull request merged**
