### PR TITLE
Moved QtImport to gui.utils + Bugfixed after running pylint

### PR DESCRIPTION
**Pull request by IvarsKarpics**
This PR includes:
* Moved QtImport to the gui.utils directory. Changed all files using QtImport
* Fixed bugs, indicated by pylint.
* Added .pylintrc configuration file.
* Added more badges to the README
* Fixed typo guidlines -> guidelines
* Removed double logging at the startup

### CODE REVIEW

**Comment by IvarsKarpics** [comment]
Please ignore the travis ci result, because the previous PR containing correct travis test is not merged.

**Comment by IvarsKarpics** [comment]
QtImport should stay in the top level, but the imports need a fix. I will reopen the PR when it is ready

**Comment by marcus-oscarsson** [comment]
Hi @IvarsKarpics 

Did someone review this before you merged ?

Cheers,
Marcus

**Comment by IvarsKarpics** [comment]
Hi @marcus-oscarsson ,

No, there was not a single comment. This PR was open for 2 weeks and it contained bugfixes (broken code found by pylint), that needed an urgent merge. Somehow I do not see the git workflow in place and I get agree when I see bugfixes not merged. Sorry, its nothing personal and I am ready to reopen the topic again during the next meeting in Lund.

**Comment by marcus-oscarsson** [comment]
Hi again,

I think it would be better to either remind everybody by sending a message or assign an appropriate reviewer. Did we actually agree on the 2 week limit, if we did I would like to see some smaller adjustments to it. I don't think its good practice that we merge our own PR's without any indication on that its going to be done. That nobody looked or commented on it is perhaps even worse and its probably more important that we focus on solving that.

Marcus

**Comment by rhfogh** [comment]
@IvarsKarpics, @marcus-oscarsson 
- First I apologise. I should normally have done something about this, but I have been extraordinarlly hung up, lately (I know, so are we all).
- Second, I agree that first assigning a reviewer or giving it a warning would be better.
- Third, one thing that slowed me down was that it seemed that this was ongoing, more bug fixes were gradually appearing. That does tempt you to wait till the fixing is finished, and there is no message to tell you when that is. Not sure how to deal with that.

**Comment by marcus-oscarsson** [comment]
We normally mark a PR as WIP (work in progress) when its ongoing which I think is a good way. Lets see if we can make this a bit more clear on our next web meeting, I think it would be good to discuss it a bit. Also maybe more importantly to see if we can get some more active reviewers !

**Comment by beteva** [comment]
Hello everybody,
assigning one or more reviewers was already discussed. Just as a reminder, we've agreed on assigning reviewers, when you think that you know who might be interested/affected by the PR you make. If you leave it open, anybody can review and accept. The drawback is that it might take longer before somebody reacts or it might be accepted by somebody, who is not using this part of the code. I am going to say a word on this during the Lund meeting.

**Pull request merged**
