### PR TITLE
Moved not used qt3 code to qt3 directory

### PR DESCRIPTION
**Pull request by IvarsKarpics**

### CODE REVIEW

**Comment by IvarsKarpics** [comment]
solves #290

**Comment by rhfogh** [comment]
@IvarsKarpics 
Hi, The PR causes a breakage in my standard mock run that I am trying to run down.
For a PR that involves over 1400 files, and that it is therefore impossible to analyse, it would make it easier to evaluate if you summarised what you are doing and why.

**Comment by marcus-oscarsson** [comment]
Would it not be better to call the directory simply qt3 ?

**Review by rhfogh — APPROVED** [review]
OK, the problem I had was in one of my classes. Sorted.

I agre with Marcus - 'qt3' might be a better name, but I am happy to merge either way.

**Comment by IvarsKarpics** [comment]
Sorry for not explaining what the PR is actually doing. For further PRs I will add more information. And I agree about the directory name: I will rename it to qt3

**Pull request merged**
