### PR TITLE
[master] Submodule update

### PR DESCRIPTION
**Pull request by IvarsKarpics**
* Added session hwobj to machine info to display disk size
* Removed not used signal/slot connection
* Added missing method to task_toolbox_brick

### CODE REVIEW

**Review by rhfogh — APPROVED** [review]
Looks good to me. I have some problems with my UI - looks like the COllect immediately button is missing, but if you can merge this in it till be a lot easier for me to test.

**Comment by rhfogh** [comment]
Ah, there were a coupld of tab indentations in MachineInfoMockup.py

There was also a MachInfoMockup.py - could that be removed?

**Comment by IvarsKarpics** [comment]
Hi @rhfogh 

The collect now button did not disappeared. You can enable/disable it via property called showCollectNowButton (Qt4_TaskToolboxBrick). I will look at the MachInfoMockup.py if it can be merged with MachineInfoMockup.py

**Comment by marcus-oscarsson** [comment]
Thanks, for next time if a PR contains more than a Submodule update, please also write that its not only a submodule update.

**Pull request merged**
