### PR TITLE
Major change

### PR DESCRIPTION
**Pull request by IvarsKarpics**
This is a major refactoring involving almost all files.
* Removed Qt4 prefix
* Renamed BlissFramework to gui
* Renamed Bricks to bricks and moved to gui
* Moved widgets to gui
* Moved ui_files to gui
* Renamed Utils to utils
* Replaced all CamelCase to snake_case
* BlissWidgets renamed to BaseWidget
* Replaced all from QtImport import * with import QtImport
* renamed Qt4_sample_changer_helper.py to sample_changer_helper.py and moved to utils
* renamed Qt4_queue_entry.py to queue_entry.py and moved to utils
* moved QLed to utils
* moved Icons.py to utils
* renamed Qt4_PlateBrick.py to PlateManipulatorBrick.py, Qt4_SampleChangerBrick3.py to SampleChangerBrick.py, Qt4_ProposalBrick2.py to ProposalBrick.py
* removed empty docstr
* added api directory and modified TreeBrick to test connection with api
* applied autopep and black
* added progress bar to the splash screen
* added Python3 support

It solves #292 #297 #298 #304 #305 #306

### CODE REVIEW

**Comment by rhfogh** [comment]
@IvarsKarpics 
Thanks, that is brilliant work!

I am not sure about the best way of reviewing it, though (and hellishly busy ahead of a test at SOLEIL next week, just for good measure). For information: Did you use automated tools to make some or all of these changes, or did you do much (or all) of it by hand? Also, did you run it though pylint or anything similar? If so, do you have the config and the output from that run?

**Comment by IvarsKarpics** [comment]
Hi @rhfogh ,

Rewritting was done manually with vim. It took some time, but now it is done and we are ready for 2.3.0. I also made a release v2.2.1 and an additional fix to HardwareRepository: see https://github.com/mxcube/HardwareRepository/pull/342

**Comment by IvarsKarpics** [comment]
And no I did not use pylint... But just for fun I can rerun it on the previous version

**Comment by IvarsKarpics** [comment]
Pylint result before and after refactoring:
0.54/10 - 5.26/10

undefined-variable 2282  - 835
trailing-whitespace 1572 - 0
invalid-name 1049 - 771
...

**Comment by rhfogh** [comment]
@IvarsKarpics 

It is clearly an improvement, which is good. But what I was getting at was that someone(s) ought to go through the output, error by error, and fix or bless them. I should certainly do my share, but I have very little time over the next ten days. Can we think of some way of sharing out the load?

**Comment by rhfogh** [comment]
@IvarsKarpics 

I am confused by your talk about 2.3.0 and 2.2.1.
I thought that the new, master, version was going to be 3.0.0, 2.3.0 was the pre-branch Qt4 version, and 2.2.1 was ancient history. Can you check / clarify? Also, I shall be doing (minor, to be sure) changes to teh pre-branch version for testing for a bnit yet.

**Comment by IvarsKarpics** [comment]
Hi @rhfogh 

Sorry, but I am also confused. I thought version 3 is for mxcube web, so for qt version we have number 2, but of course it makes sense to call it v3 because HardwareRepository v3 in March will be released.

**Comment by rhfogh** [comment]
You have a  point. Can anyone else clarify?

**Comment by rhfogh** [comment]
@IvarsKarpics 
Looking at http://mxcube.github.io/mxcube/ it says on hte front page that the latest stable release is 2.3.1. In the minutes of the face-to-face meeting (November 15) it says that version 2.3.0 was made at that meeting by brqanching off master (which owuld become 3.0.0) but OK, these are HR repository versions.

Looking at https://github.com/mxcube/mxcube/releases one notes release 2.3.1 dated July 4 2018 (presumably that is the 'latest stable relase'?). The we have release 2.2.1 from August 16, and 2.2.2 and 2.3.0 from yesterday. The new 2.3.0 contains code from yesterday, that is more than half a year after the previous release 2.3.1 was issued.

This is really complicated. Can someone else provide an overview?

**Comment by IvarsKarpics** [comment]
Hi @rhfogh 

I started to edit mxcube releases, because there is a mess with the numbering. I will go once again through and assign numbers based on the release date.

**Comment by marcus-oscarsson** [comment]
Hi,

Thanks for all these changes its as you understand quite complicated to get a good idea of what happened in detail.

It seems like alot of improvements judging from your comments, a question whats the API folder your refeering to ?

About the versioning, it seems like there is some mistake with the tag names right ?
-   There are two 2.2.2 one that starts with "v" and one without ?
-   There is also a v2.3.0 that is older than 2.2.2 (without v)

That is maybe where some of the confusion lies ?

The versioning of HardwareRepository is another matter and its versioned independently. The current master on HardwareRepository will become 3.0.0 when its released. Whether we append alpha or beta to it remains to be seen perhaps.

I assume that the current stable release of MXCuBE2 (Qt3 or Qt4) uses HardwareRepository 2.3.0, just
as the current version of MXCuBE3 (Web) uses HardwareRepository 2.2.0. The aim with all this is that both MXCuBE3 and MXCuBE2 will use HardwareRepository 3.x.y-z for instance 3.0.0-alpha in March.

Does it clarify something or did I misunderstand the question ?

**Comment by IvarsKarpics** [comment]
Hi @marcus-oscarsson ,

From now api folder is empty and has just a beamline_setup in the __init__.py  I think the idea about api is not dead and It would help to write a cleaner code. Also we could run travis pytest agains api, because Qt gui testing via travis is not easy.

**Comment by marcus-oscarsson** [comment]
Oh, great I'm happy to hear that you dont think the API idea is dead. I see your intention then thanks :)

**Comment by IvarsKarpics** [comment]
I added also python3 support. see https://github.com/mxcube/HardwareRepository/pull/343 for changes in the HardwareRepository.
Tested with python3.6, Qt5 on ubuntu18

**Comment by IvarsKarpics** [comment]
Whats the status of the PR (it is already 10 days old)? Can I just merge it and we see what happens?

**Comment by marcus-oscarsson** [comment]
Hi @IvarsKarpics, sorry I've been away for a few days so I have not have had the possibility to check this PR. Its also a really big PR so its difficult to make a qualitative judgement. I understand that its sometimes difficult to make large structural changes and keep the PR's small ...

**Comment by IvarsKarpics** [comment]
Hi @rhfogh ,

Thank you for merging the PR. As it is a huge change I am ready for comments,bug reports, questions and etc :)

**Comment by marcus-oscarsson** [comment]
Hi @IvarsKarpics, all fine except for that it was me who merged it :)

**Pull request merged**
