### PR TITLE
Cleared circular imports and changed to getHardwareRepository() 

### PR DESCRIPTION
**Pull request by rhfogh**
Goes with similar PR for mxcube

### CODE REVIEW

**Comment by rhfogh** [comment]
Additional changes added

**Comment by IvarsKarpics** [comment]
Is this work in progress?

**Comment by rhfogh** [comment]
@IvarsKarpics 
Not any more, no. But I discovered when I had made the supposedly correct PR that the tests failed, had to change the test, and added a couple of clean-up things I came across. It is finished now AFAIK.

**Comment by rhfogh** [comment]
Oops, I messed up the PR - and I had not realised that you were trying to tell me that there was something wrong. Anyway, it ought to work now.

**Comment by rhfogh** [comment]
Thanks!

**Pull request merged**
