### PR TITLE
Repeat of PR449 to the dev branch instead of master

### PR DESCRIPTION
**Pull request by agruzinov**

### CODE REVIEW

**Review by rhfogh — APPROVED** [review]
That should be fine.

**Comment by beteva** [comment]
OK to merge

**Comment by rhfogh** [comment]
That looks fine. And thanks for getting it done so fast, committing from 
the train is 'above and beyond'.

So after that, develop should be the top branch to keep working on, 
right? Out of curiosity, Looking at the commit tree, there are a lot of 
commits registered against agruzinov/p11_qt_update. Are they already 
included in develop now, through some other branch, or are they awaiting 
a new PR?

Rasmus

**Comment by agruzinov** [comment]
They are not yet included. I need to rebase and submit a new PR.

**Pull request merged**
