### PR TITLE
Added minutes of September developers' meeting

### PR DESCRIPTION
**Pull request by rhfogh**

### CODE REVIEW

**Comment by IvarsKarpics** [comment]
Thank you @rhfogh for the minutes. I looked through and they look fine. Just a one remark: In the status report I did not say about mxcube-epics. I guess that sentence belongs to LNLS?

**Comment by marcus-oscarsson** [comment]
Thanks @rhfogh  I have a few changes to make,

For the section about ESRF:
The plan is to get the latest version of MXCuBE 3 installed by January, however our shutdown ends in August, so that's when we will take first users. The plan is to have everything running for March when we get beam to the experimental hutches. In house test usage might start in May depending on how things goes before that.

The section about EMLB-HH

Is it not HC-Lab ?

**Comment by rhfogh** [comment]
Dear Ivars, Marcus,

Thanks for the corrections (and so fast, too ;-) ).

I have put a modified document into the pull request.

Yours,

Rasmus

On 25/09/2019 08:27, Marcus Oscarsson wrote:
> The plan is to get the latest version of MXCuBE 3 installed by January, 
> however our shutdown ends in August, so that's when we will take first 
> users. The plan is to have everything running for March when we get beam 
> to the experimental hutches. In house test usage might start in May 
> depending on how tings goes before that.

-- 
Rasmus Fogh
Cambridge, UK.

**Review by IvarsKarpics — APPROVED** [review]

**Comment by IvarsKarpics** [comment]
@rhfogh  I think you did not commit the file.

**Comment by rhfogh** [comment]
@IvarsKarpics 
Did that help?

**Pull request merged**
