### PR TITLE
[master] Submodule update

### PR DESCRIPTION
**Pull request by IvarsKarpics**

### CODE REVIEW

**Comment by beteva** [comment]
Hello @IvarsKarpics, your submodule update has been done before accepting pull request #261. Would it will be possible to accept it and than do again the submodule update?

**Comment by IvarsKarpics** [comment]
Hi @beteva ,

I accepted the PR by myself, because the mxcube was not running (missing the monkey patching). #261 was merged a month ago. Do you mean latest PR to HardwareRepository?

**Comment by beteva** [comment]
Yes, indeed, I was talking about the HardwareRepository PR.

**Comment by IvarsKarpics** [comment]
Ok, I will follow the PRs and do the submodule update when they are merged.

**Pull request merged**
