### PR TITLE
Msbbrick pressbutton

### PR DESCRIPTION
**Pull request by natxo14**
Hi there,

At the beginning I started working on MotorSpinBoxBrick trying to:

* make right and left buttons 'pressable' : while mouse button was down, 'move' order will be executed until the button was released. 
* fix issues related to the 'state' that impeded to work with BlissMotor.py

Finally I decided to 'fork' the brick and create a clone for the gui/bricks/ESRF folder : didn't know if that behaviour was needed elsewhere and didn't want to mess up with another control systems.
If everyone's happy, it'll be my pleasure to change the generic MotorSpinBoxBrick

A pull request on HardwareObjects for BlissMotor to come to match with this.
Thanks

### CODE REVIEW

**Comment by vrey01** [comment]
Hi there,

The "pressable" feature of right and left button could be a configurable property of the brick, then the code would fit all sites.

**Comment by IvarsKarpics** [comment]
Hi @natxo14 . I agree with @vrey01 . One should instead of creating a new brick add this feature as a property (by default set it to False). It would be useful for others as well.

**Comment by marcus-oscarsson** [comment]
Hey @natxo14 or good evening maybe :) Really well done !, 

It looks like there are few changes that the others already pointed out that we can put in place to make this even more general.

I'm working as kinder-garden tomorrow :) but I'm a free for a quick chat if needed 

Thanks,
Marcus

**Comment by natxo14** [comment]
So, I made changes to change the buttons' behaviour with a property (oneClickPressButton).

And sorry again, but I had to make some extra changes to make the brick work: the states strike back!
I changed the STATE_COLORS order to match the HardwareObjectState list of states.
Also, there was code checking the state of the motor like:
`elif state in (
            self.motor_hwobj.motor_states.LOWLIMIT,
            self.motor_hwobj.motor_states.HIGHLIMIT,
        ):`
But as motor_states is no longer defined and as I guess that in a GUI brick we should work with 'generic' HardwareObject states and not the specific ones (and the as state list in HardwareObjectState is quite short), I've refactored it this way:
`elif state in (
            self.motor_hwobj.STATES.READY,
        ):`

Any feedback will be welcome.
Thanks!

**Comment by IvarsKarpics** [comment]
Hi @natxo14 .
It looks like we faced the same issue at the same time. I changes already the MotorSpinboxBrick and added new method get_state_color in Colors.py. See: #392
I can merge your PR and then update my one with your changes.

**Comment by natxo14** [comment]
Hi @IvarsKarpics : seems good to me, feel free to make the changes you consider necessary

**Pull request merged**
