### PR TITLE
A try to create a state machine

### PR DESCRIPTION
**Pull request by IvarsKarpics**
- Moved example gui files to ExampleFiles
- New brick to visualize state machine. It is a try to create a state machine (implemented in hwobj) that controls the behavior of GUI (disable/enable certain controls)
- Added feature to sync queue with ispyb. Diffraction plan is  added to the sample after sync

### CODE REVIEW

**Comment by mguijarr** [comment]
@IvarsKarpics hello :) I see a lot of work in this PR. I have to admit I have no time at the moment to review all changes and trying to understand what it does exactly - maybe you can shed some light on what you're trying to achieve ? Looks interesting.

**Comment by mguijarr** [comment]
The other thing I would like to say is that development is going at quite a fast pace in the master branch, although I am afraid a lot of people (me included) do not know why some decisions are taken and can miss the global picture - I would say we need more consensus maybe. At ESRF we are focused on MXCuBE 3 at the moment, and our beamlines upgrades, which doesn't help for setting up plans for the future, but I am also thinking of other partners too... Does everybody follow ?

**Comment by IvarsKarpics** [comment]
Hi @mguijarr 

This last one is a try to create something similar to Finite state machine within mxcube. For sure this is not a final version, some big upgrade, branching or whatsoever. I did not want to miss the code, so I decided to   create a PR. However there are some features that circumnavigate feature board already years. For example the sync of diffraction plan from ispyb.
Regarding the global picture, it is difficult to say... This is a question to be raised during the meeting
I know that you have a high work load and I was thinking if some one else could also review the code and merge pull requests for Qt4 version.

**Comment by IvarsKarpics** [comment]
I will split this PR in several PRs

**Pull request closed without merging**
